services:
  nginx_frontend_profe:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_KEY=${API_KEY}
      - API_UPSTREAM=${API_UPSTREAM:-http://host.docker.internal:8000}
    ports:
      - "8090:8090"
