services:
  rotator_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rotator-api
    ports:
      - "8000:8000"
    volumes:
      - crypto_keys:/app/keys

volumes:
  crypto_keys:
