services:
  initial_ldap_nginx_frontend:
    build:
      context: ./nginx-frontend/
      dockerfile: Dockerfile
    container_name: initial_ldap_nginx_frontend_container
    environment:
      - API_KEY=${API_KEY}
      - API_UPSTREAM=${API_UPSTREAM:-http://host.docker.internal:8083}
    ports:
      - "8090:8090"

  initial_ldap_api:
    build:
      context: ./LDAP/fastapi/
      dockerfile: Dockerfile
    container_name: initial_ldap_api_container
    ports:
      - "8083:8083"
    environment:
      API_KEY: ${API_KEY}
      LDAP_HOST: openldap
      LDAP_PORT: "389"
      LDAP_BASE_DN: "dc=example,dc=com"
    # depends_on:
    #   - initial_openldap
    # networks:
    #   - initial_ldap_network

  initial_openldap:
    image: osixia/openldap:1.5.0
    container_name: initial_openldap_container
    hostname: ldap.example.com
    environment:
      LDAP_ORGANISATION: "Example Corp"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "adminpassword"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - initial_ldap_data:/var/lib/ldap
      - initial_ldap_config:/etc/ldap/slapd.d
    networks:
      - initial_ldap_network

  initial_phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: initial_phpldapadmin_container
    hostname: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - initial_openldap
    networks:
      - initial_ldap_network


volumes:
  initial_ldap_data:
  initial_ldap_config:

networks:
  initial_ldap_network:
